### ISSUE TITLE
USER STORY: View Post List

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#1]
As a **site user** I can **view a paginated list of posts** so that **I can briefly view many posts before selecting one to view in detail**

### Acceptance Criteria

- [x] Post list displays all current posts
- [x] Posts in post list link to detailed view of selected post
- [x] Post list displays post title, creators name, number of likes and a featured image

### Tasks

- [x] Create display section for singular post
- [x] Connect posts in database to post list to be displayed
- [x] Paginate post list
