### ISSUE TITLE
USER STORY: Google Sign-in

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#10]
As a **site user** I can **sign in using my google account** so that **I can quickly and easily register an account in one click**

### Acceptance Criteria

- [ ] User can use a google button to use their google account to sign in

### Tasks

- [ ] Add button to the sign up page for google sign in
- [ ] Use the users google account details to create an account for them

**Comment by alexkavanagh-dev** [comment]
User Story will not be added in this version of the website. Could be added in the future
