### ISSUE TITLE
USER STORY: Featured Posts

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#11]
As a **site admin** I can **select certain posts to be featured** so that **I can highlight specfic posts that I found to be well done**

### Acceptance Criteria

- [x] Only site admin has access to making posts featured
- [x] Featured posts have a distinctive label showing them as featured

### Tasks

- [x] Add boolean field in post model for featured status
- [x] Create button for admin to select featured posts
