### ISSUE TITLE
USER STORY: Forgot Password

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#13]
As a **registered user** I can **click a forgot password button on the login page** so that **I can reset the password to my account upon forgetting it**

### Acceptance Criteria

- [ ] Button on login page for forgot password
- [ ] Allow user to enter email address used for sign up to reset password
- [ ] If email address is not connected to an account, inform user of this
- [ ] Upon confirming their identity through an email reset link, the user can enter a new password to use

### Tasks

- [ ] Create button on login page for forgotten password
- [ ] Create forgot password page
- [ ] Take email address from user used in account registration
- [ ] Show error/warning if email address has not been used for a user in the system
- [ ] Send reset password email to email address entered by user
- [ ] Allow user to use link in reset password to enter a new password

**Comment by alexkavanagh-dev** [comment]
User Story will not be added in this version of the website. Could be added in the future
