### ISSUE TITLE
USER STORY: Sort Posts

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#14]
As a **site user** I can **select an order to sort posts by on the post list view** so that **I can view newer/older/popular posts easier**

### Acceptance Criteria

- [ ] Dropdown menu contains list of options to user for sorting
- [ ] Default sorting is newest to oldest
- [ ] Options to at least sort by post date and post likes

### Tasks

- [ ] Create dropdown menu with options for sorting
- [ ] Filter posts by selected option once chosen by user

**Comment by alexkavanagh-dev** [comment]
User Story will not be added in this version of the website. Could be added in the future
