### ISSUE TITLE
USER STORY: View my Profile

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#15]
As a **registered user** I can **view my own profile** so that **I can quickly see all my posts, comments and liked posts in one place**

### Acceptance Criteria

- [ ] Button in navbar for profile appears once user is logged in
- [ ] Profile button brings user to their own page
- [ ] Profile page displays users posts, comments and liked posts

### Tasks

- [ ] Create profile button in navbar for logged in users
- [ ] Create page template for profiles
- [ ] Use data in database for users to create and insert relevant information on their profile page

**Comment by alexkavanagh-dev** [comment]
User Story will not be implemented in this version of the website. Could be added in future.
