### ISSUE TITLE
USER STORY: Open Post

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#2]
As a **site user** I can **click on a post** so that **I can see a detailed view of a post**

### Acceptance Criteria

- [x] Posts in post view link to a detailed view of the selected post when clicked

### Tasks

- [x] Create posts in post list as links
- [x] Link each post to its own detailed view
