### ISSUE TITLE
USER STORY: View Likes

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#3]
As a **site user** I can **see the number of likes a post has** so that **I can see at a glance which post other users enjoyed the most**

### Acceptance Criteria

- [x] Post likes can be viewed clearly in post view and detailed view
- [x] Use an icon clearly representing likes for posts

### Tasks

- [x] Add field to post model for likes
- [x] Find suitable icon for likes
- [x] Display likes on posts in post list and detailed view using the icon and number of likes from database
