### ISSUE TITLE
USER STORY: View Comments

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#4]
As a **site user** I can **see comments on a post** so that **I can read feedback from other users on posts**

### Acceptance Criteria

- [x] Comments display under posts in detailed view
- [x] Comments display from newest to oldest
- [x] Comments are clearly seperated from one another and show which user posted it

### Tasks

- [x] Add model for comments
- [x] Display comments underneath posts
