### ISSUE TITLE
USER STORY: Register Account

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#5]
As a **site user** I can **register an account** so that **I can like posts, comment on posts and create my own posts**

### Acceptance Criteria

- [x] User can create unique username

### Tasks

- [x] Add authentication for users in django
- [x] Create sign up page with form to register account
- [x] Link to sign up page in navbar
