### ISSUE TITLE
USER STORY: Like/Unlike posts

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#6]
As a **registered user** I can **like/unlike posts** so that **I can share positive feedback to posts I liked**

### Acceptance Criteria

- [x] User can click 'like' icon to like a post and click again to unlike a post
- [x] Likes immediately register and is reflected in the likes counter on a post
- [x] Like/unlike feature is only available to registered users

### Tasks

- [x] Make 'likes' icon a button to add a like to post
