### ISSUE TITLE
USER STORY: Manage Posts

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#7]
As a **site admin** I can **manage posts made by other users** so that **I can manage and remove questionable content on my website**

### Acceptance Criteria

- [x] Site admin can edit and delete posts made by other users
- [x] Site admin can approve posts before they are shown on the website
- [x] Posts can only be edited/deleted by the post creator and the site admin

### Tasks

- [x] Set posts to be manageable by the site admin aswell as the post creator
- [x] Add a boolean field to the post model for approved/unapproved
