### ISSUE TITLE
USER STORY: Search Site

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/computer-system-showcase#9]
As a **site user** I can **search by keyword** so that **I can easily find specfic content related to certain words**

### Acceptance Criteria

- [x] Search bar displayed in navbar
- [x] Words entered into search bar will filter posts containing those words
- [x] Once search terms are entered, a search page will display related posts or inform user that there was no related posts

### Tasks

- [x] Create search bar in navbar
- [x] Make search bar a form element to take keywords
- [x] Use keywords in search bar to filter database of posts
- [x] Display search results on a new page
